export const PRIMARY_CATEGORIES = [
  'FOOD_AND_DRINK', 'TRANSPORTATION', 'SHOPS', 'ENTERTAINMENT',
  'PERSONAL_CARE', 'HEALTH_WELLNESS', 'HOME_IMPROVEMENT', 'GENERAL_MERCHANDISE',
  'TRAVEL', 'RENT_UTILITIES', 'LOAN_PAYMENTS', 'GENERAL_SERVICES',
  'GOVERNMENT_AND_NON_PROFIT', 'BANK_FEES', 'TRANSFER_IN', 'TRANSFER_OUT'
]

export const CATEGORY_LABELS = {
  FOOD_AND_DRINK: 'Food & Drink',
  TRANSPORTATION: 'Transportation',
  SHOPS: 'Shopping',
  ENTERTAINMENT: 'Entertainment',
  PERSONAL_CARE: 'Personal Care',
  HEALTH_WELLNESS: 'Health & Wellness',
  HOME_IMPROVEMENT: 'Home Improvement',
  GENERAL_MERCHANDISE: 'General Merchandise',
  TRAVEL: 'Travel',
  RENT_UTILITIES: 'Rent & Utilities',
  LOAN_PAYMENTS: 'Loan Payments',
  GENERAL_SERVICES: 'General Services',
  GOVERNMENT_AND_NON_PROFIT: 'Gov & Non-Profit',
  BANK_FEES: 'Bank Fees',
  TRANSFER_IN: 'Transfer In',
  TRANSFER_OUT: 'Transfer Out'
}

export const CATEGORY_COLORS = {
  FOOD_AND_DRINK: '#FF6B6B',
  TRANSPORTATION: '#4ECDC4',
  SHOPS: '#45B7D1',
  ENTERTAINMENT: '#96CEB4',
  PERSONAL_CARE: '#FFEAA7',
  HEALTH_WELLNESS: '#DDA0DD',
  HOME_IMPROVEMENT: '#98D8C8',
  GENERAL_MERCHANDISE: '#F7DC6F',
  TRAVEL: '#BB8FCE',
  RENT_UTILITIES: '#85C1E9',
  LOAN_PAYMENTS: '#F0B27A',
  GENERAL_SERVICES: '#A9DFBF',
  GOVERNMENT_AND_NON_PROFIT: '#D5DBDB',
  BANK_FEES: '#F1948A',
  TRANSFER_IN: '#AED6F1',
  TRANSFER_OUT: '#FAD7A0'
}

export const DETAILED_CATEGORIES = {
  FOOD_AND_DRINK: [
    'FOOD_AND_DRINK_BEER_WINE_LIQUOR', 'FOOD_AND_DRINK_COFFEE', 'FOOD_AND_DRINK_FAST_FOOD',
    'FOOD_AND_DRINK_GROCERIES', 'FOOD_AND_DRINK_RESTAURANT', 'FOOD_AND_DRINK_VENDING_MACHINES',
    'FOOD_AND_DRINK_OTHER_FOOD_AND_DRINK'
  ],
  TRANSPORTATION: [
    'TRANSPORTATION_BIKES_AND_SCOOTERS', 'TRANSPORTATION_GAS', 'TRANSPORTATION_PARKING',
    'TRANSPORTATION_PUBLIC_TRANSIT', 'TRANSPORTATION_TAXIS_AND_RIDE_SHARES', 'TRANSPORTATION_TOLLS',
    'TRANSPORTATION_OTHER_TRANSPORTATION'
  ],
  SHOPS: [
    'SHOPS_CLOTHING_AND_ACCESSORIES', 'SHOPS_COMPUTERS_AND_ELECTRONICS', 'SHOPS_CONVENIENCE_STORES',
    'SHOPS_DEPARTMENT_STORES', 'SHOPS_HOBBY_AND_COLLECTIBLES', 'SHOPS_PET_SUPPLIES',
    'SHOPS_SPORTING_GOODS', 'SHOPS_SUPERSTORES', 'SHOPS_OTHER_SHOPS'
  ],
  ENTERTAINMENT: [
    'ENTERTAINMENT_CASINOS_AND_GAMBLING', 'ENTERTAINMENT_MUSIC_AND_AUDIO', 'ENTERTAINMENT_SPORTING_EVENTS',
    'ENTERTAINMENT_TV_AND_MOVIES', 'ENTERTAINMENT_VIDEO_GAMES', 'ENTERTAINMENT_OTHER_ENTERTAINMENT'
  ],
  PERSONAL_CARE: [
    'PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS', 'PERSONAL_CARE_HAIR_AND_BEAUTY',
    'PERSONAL_CARE_LAUNDRY_AND_DRY_CLEANING', 'PERSONAL_CARE_OTHER_PERSONAL_CARE'
  ],
  HEALTH_WELLNESS: [
    'HEALTH_WELLNESS_DENTIST', 'HEALTH_WELLNESS_DOCTOR', 'HEALTH_WELLNESS_HOSPITALS',
    'HEALTH_WELLNESS_PHARMACIES_AND_SUPPLEMENTS', 'HEALTH_WELLNESS_OTHER_HEALTH_WELLNESS'
  ],
  HOME_IMPROVEMENT: [
    'HOME_IMPROVEMENT_FURNITURE', 'HOME_IMPROVEMENT_HARDWARE', 'HOME_IMPROVEMENT_REPAIR_AND_MAINTENANCE',
    'HOME_IMPROVEMENT_SECURITY', 'HOME_IMPROVEMENT_OTHER_HOME_IMPROVEMENT'
  ],
  GENERAL_MERCHANDISE: [
    'GENERAL_MERCHANDISE_DISCOUNT_STORES', 'GENERAL_MERCHANDISE_ONLINE_MARKETPLACES',
    'GENERAL_MERCHANDISE_WHOLESALE', 'GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE'
  ],
  TRAVEL: [
    'TRAVEL_FLIGHTS', 'TRAVEL_HOTELS_AND_MOTELS', 'TRAVEL_RENTAL_CARS', 'TRAVEL_OTHER_TRAVEL'
  ],
  RENT_UTILITIES: [
    'RENT_UTILITIES_GAS_AND_ELECTRICITY', 'RENT_UTILITIES_INTERNET_AND_CABLE', 'RENT_UTILITIES_RENT',
    'RENT_UTILITIES_SEWAGE_AND_WASTE', 'RENT_UTILITIES_TELEPHONE', 'RENT_UTILITIES_WATER',
    'RENT_UTILITIES_OTHER_UTILITIES'
  ],
  LOAN_PAYMENTS: [
    'LOAN_PAYMENTS_CAR_PAYMENT', 'LOAN_PAYMENTS_CREDIT_CARD_PAYMENT',
    'LOAN_PAYMENTS_STUDENT_LOAN_PAYMENT', 'LOAN_PAYMENTS_OTHER_PAYMENT'
  ],
  GENERAL_SERVICES: [
    'GENERAL_SERVICES_ACCOUNTING_AND_FINANCIAL_PLANNING', 'GENERAL_SERVICES_AUTOMOTIVE',
    'GENERAL_SERVICES_CHILDCARE', 'GENERAL_SERVICES_CONSULTING_AND_LEGAL',
    'GENERAL_SERVICES_EDUCATION', 'GENERAL_SERVICES_INSURANCE', 'GENERAL_SERVICES_POSTAGE_AND_SHIPPING',
    'GENERAL_SERVICES_STORAGE', 'GENERAL_SERVICES_OTHER_GENERAL_SERVICES'
  ],
  GOVERNMENT_AND_NON_PROFIT: [
    'GOVERNMENT_AND_NON_PROFIT_DONATIONS', 'GOVERNMENT_AND_NON_PROFIT_GOVERNMENT_FEES',
    'GOVERNMENT_AND_NON_PROFIT_TAX_PAYMENT'
  ],
  BANK_FEES: [
    'BANK_FEES_ATM_FEES', 'BANK_FEES_FOREIGN_TRANSACTION_FEES',
    'BANK_FEES_OVERDRAFT_FEES', 'BANK_FEES_OTHER_BANK_FEES'
  ],
  TRANSFER_IN: [
    'TRANSFER_IN_CASH_ADVANCES', 'TRANSFER_IN_DEPOSIT', 'TRANSFER_IN_INVESTMENT_AND_RETIREMENT',
    'TRANSFER_IN_SAVINGS', 'TRANSFER_IN_OTHER_TRANSFER_IN'
  ],
  TRANSFER_OUT: [
    'TRANSFER_OUT_INVESTMENT_AND_RETIREMENT', 'TRANSFER_OUT_SAVINGS',
    'TRANSFER_OUT_WITHDRAWAL', 'TRANSFER_OUT_OTHER_TRANSFER_OUT'
  ]
}

export function getDetailedLabel(code) {
  if (!code) return 'Uncategorized'
  return code.split('_').map(w => w.charAt(0) + w.slice(1).toLowerCase()).join(' ')
}

export function getPrimaryFromDetailed(detailed) {
  if (!detailed) return null
  for (const primary of PRIMARY_CATEGORIES) {
    if (detailed.startsWith(primary + '_') || detailed === primary) return primary
  }
  return null
}

export const ALL_DETAILED = Object.entries(DETAILED_CATEGORIES).flatMap(([primary, list]) =>
  list.map(code => ({ code, primary, label: getDetailedLabel(code) }))
)
